// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuwxA-w62y7k6thaKqAVtmXe0Ibz_3ASk',
    appId: '1:217615616379:web:944a2dbe8d0361721dd5de',
    messagingSenderId: '217615616379',
    projectId: 'mux-sample',
    authDomain: 'mux-sample.firebaseapp.com',
    databaseURL: 'https://mux-sample-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mux-sample.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPLCq7xulbz0O5IhP-8NyaenUcyzJqf-M',
    appId: '1:217615616379:android:e9edb59d86f6f2ab1dd5de',
    messagingSenderId: '217615616379',
    projectId: 'mux-sample',
    databaseURL: 'https://mux-sample-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mux-sample.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOSNElEfUS3tW1sXxH9AhXUCsSUv1DQiY',
    appId: '1:217615616379:ios:9113c8804e1aaefa1dd5de',
    messagingSenderId: '217615616379',
    projectId: 'mux-sample',
    databaseURL: 'https://mux-sample-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mux-sample.appspot.com',
    iosClientId: '217615616379-jphitu21cemuu70ceebnvrhrrh0784tl.apps.googleusercontent.com',
    iosBundleId: 'com.example.mux',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOSNElEfUS3tW1sXxH9AhXUCsSUv1DQiY',
    appId: '1:217615616379:ios:9113c8804e1aaefa1dd5de',
    messagingSenderId: '217615616379',
    projectId: 'mux-sample',
    databaseURL: 'https://mux-sample-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mux-sample.appspot.com',
    iosClientId: '217615616379-jphitu21cemuu70ceebnvrhrrh0784tl.apps.googleusercontent.com',
    iosBundleId: 'com.example.mux',
  );
}
